sudo: false
language: rust
cache: cargo
rust:
- beta
- stable
before_script:
- "(cargo install mdbook --force || true)"
script:
- PATH=$PATH:/home/travis/.cargo/bin mdbook test
- PATH=$PATH:/home/travis/.cargo/bin mdbook build
- cargo run --bin lfp src
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" &&  bash
  deploy-gh-pages.sh
env:
  global:
  - secure: h5DdE1NJoyU5h/lA+tCn2ViWBWzPFMgskqF6DmcjTza+U9ktYv8gq02KKoCv9TqZVQspU4gWDp+EVRzr/rIzohqijngdqXO3Zfe6ZnAU1R/TwofNo1Mbt+nbEqCYB7xMkpRzcW1vWeWedzSurSrRzIk6P6lk72REVnjIGn4LSewyn2mFphV2dTHtl0VNgCtIDUYJoHAjm9tPF2zbEv+c7zmC3+pCG/HxuIFIaMHuiE6NCsk/kq48Thk2mObFQ004FDIYOBAmZyqMQrP8ibrZ0L3Qhv/IVVMTlziwlKNopEL3Q29q1VlxvktsLuWZYFjDU4ljzfcN+Mk9Uh5aftPIJdxNRnw2JFuBth5dm7Pf9pbgFCQvjczDA5kA+i5GnwD6lhom6cGkhSQA0mNWrFw4MXF07NY7yceNfJJJFNfXkiFq601oI9E/hsyT24161TaJ5Ev7BlIsrKgjVDxwSBQE1UMkeWsjruzaoE33rmO55a85AFRAyugyRg5+TlS7s5kLWOj8YDsC/fu7rN5ZyQRQs/tJ0yU6eDfhpSSLZeOpZBdY07RGlF0EnSMPLoi1iS1eDYxBKTztQN2W8g1io7+PEBp1Qq3cHHd+9Zm8dquGPl+iRI5NeNp+mFg6MDNy1bL4xah6p2koBlTfnMgYFil7cXFnDlNGZKCktp9J54V89CQ=
