sudo: false
language: rust
cache: cargo
rust:
- beta
- stable
before_script:
- "(cargo install mdbook --force || true)"
script:
- PATH=$PATH:/home/travis/.cargo/bin mdbook test
- PATH=$PATH:/home/travis/.cargo/bin mdbook build
- cargo run --bin lfp src
deploy:
  provider: releases
  api_key:
    secure: mFkN1r8miy+l+mApdqHs1uD1rsMrutIZNQOhNG5sPx4+WKUoAGIuxURQz0p3xoHpmJoeW4+6I9gnoDuZwxJcR4NPfZGjaaPmPUBBWNIER1zo6rwwAPMlaXS0A13/U37/BuYYA6cAwhYZLXWA3c4Yv6zPTUHZQya/GWQJbdqfU7Vl+Stlm2eGE1R0SnUqj8Zu0O4rZKoowips3SBXhjGa2sqSbcTN663Km6utDWFGm8AIqXt/T6pKmP4tnbTSyh8zV282ReH/OpI4bFmCaHtinnuKN/9YVMKYr7FX7Mj4E7OsAeRulVd0tcczxB01ZuJImtGlOhrnfP/qSGuxsYEHhjYGVvUHBJ9jcSS9Qm1t8BuCy1R6gGpOj5FfLjeEh9M8h0YQU8tUWzNaCez+w8hFaef3Y20Dn+lsDAju3Uc6QQCsdR251di4dCUqOpKPzfX1+IOe1eTec2ufPPTBDfVbmc3fURtat0YOtkzhgaF5PMwPhOJSv2JMJJ68iIAxXKhpzNPPJ9vXTmcxkzjSofD4UM8OzEgLup//lfipfD+iiqE/9Mg/ccrkrM5WcBiWiqYTGfA+T/dje4e7geTcKk647Br9oo79Q2adW+lVM3VeCah1p+wBdgj463YTf82yF+86Lye3je/E4ZUgAnC9/p/kd3mv4JFKecZl/o2zPDiLL6I=
  file: "/book"
  on:
    repo: rust-vietnam/book
