sudo: false
language: rust
cache: cargo
rust:
- beta
- stable
before_script:
- "(cargo install mdbook --force || true)"
script:
- PATH=$PATH:/home/travis/.cargo/bin mdbook test
- PATH=$PATH:/home/travis/.cargo/bin mdbook build
- cargo run --bin lfp src
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" &&  bash
  deploy-gh-pages.sh
env:
  global:
  - secure: wwGBDWJqXSH4qFGHiNh3+kYWaZSm81aJEMmLm1MJwe27ZZA+6vqsr3kaDm9AYlneeddfTGt6cEtVolCNGY1SGrCGdhAOL4unc+/4Ct1jLB3yZaV5upbGnr/nJi8AvAUM/r06igSJBe3oRiA3B+imOC4XxHpZpL/rWapAe8qiLpElrH2AhcrofeSuX/R+yg1riUbkqYCP/YHzqqrRvAIvLyVI1vopKgwoRjdjj0Xxo72OWRfifXTFX3RKg3o3fHTbZ2SX0DXotUe6W1a2q4LDct8Coovv/ir7PpHMsX10Th/Rj3P9f050S/EgqQanWDmk3xwEEv3Zx63+9blPC6xskmdsxlpWA9+9SYXZSjTy0jhMOCUclJTaTt6vS7gsu6OFkHn2JHN2LJr8+DrRxCjWt899bDwpbaGEw7VhgdAP8LDh3Pqkp1EmL+Cn4Gkq3i0pUVaJEij/wWnqwzJqwVY8lbNZX2ZFqpYyblArTZAX2rj8LVY6CO5mE7ExqomiFXFvS3/HlayyBcbEcH4t9px5JsGG6JdPM9An0atzVqYjhgd9mtut1jv56iDE8HR5uWR5YH35ciLDQbbq36DWbbbFh6z6KWQhUXf7qMf1E1cXWynVFBwEbolgY/qwVkyXRNr8EkR5a5ssfv7US7fowSI4/PSxGQ2gnymO7HECwAYGNJ0=
